# Nome da aplicação (usado em logs e monitoramento)
spring.application.name=backend


# ================================
# Configuração do banco de dados
# ================================

# URL de conexão com o banco PostgreSQL
# O valor é obtido da variável de ambiente DB_URL
spring.datasource.url=${DB_URL}

# Usuário do banco
spring.datasource.username=${DB_USER}

# Senha do banco
spring.datasource.password=${DB_PASSWORD}


# ================================
# Configuração do JPA / Hibernate
# ================================

# Define como o Hibernate irá lidar com o schema do banco
#
# update → cria ou atualiza tabelas automaticamente
# create → recria tudo a cada execução
# validate → apenas valida se o schema existe
# none → não faz nada
spring.jpa.hibernate.ddl-auto=update


# Mostra no console as queries SQL geradas automaticamente
# Muito útil para debug durante o desenvolvimento
spring.jpa.show-sql=true


# Define o dialeto do banco usado pelo Hibernate
# Isso permite que o ORM gere SQL compatível com PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Porta do servidor backend
server.port=8080